version: '3.1'
services:
  auth-server:
    build: ./auth-service
    container_name: auth-server
    ports:
      - "8181:8181"
    depends_on:
      - auth-db
    environment:
      - AUTH_DB_HOST=auth-db
      - AUTH_DB_PORT=5432
      - AUTH_DB_NAME=auth_db
      - AUTH_POSTGRES_USER=postgres
      - AUTH_POSTGRES_PASSWORD=1
      - ACCESS_TOKEN_EXPIRE_LENGTH=1800000
      - REFRESH_TOKEN_EXPIRE_LENGTH=86400000
      - ACCESS_KEY_SECRET_VALUE=SkFfMHotTzhxbEtRQ1AyZkwxVU1LQjVoXyxFNnNkdHdhQkRac0ZueTlJLnchTnY3eDVKQ1lHM1J1T3JNaT9YcFRFR2h2NA==
      - REFRESH_KEY_SECRET_VALUE=dkpJM3ctblBtVDdMUyxyWjggNWVSSmZTIUREWnkwY2tBcGZPcUVhWWtIZzR3VF9VcTF4MkhpOSBiTF82TmdYPy5vQ2JVTVY=

  auth-db:
    image: postgres:15-alpine
    volumes:
      - /var/lib/postgresql/tms/auth
    container_name: auth-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1

  task-server:
    build: ./task-service
    container_name: task-server
    ports:
      - "8080:8080"
    depends_on:
      - task-db
    environment:
      - TASK_DB_HOST=task-db
      - TASK_DB_PORT=5432
      - TASK_DB_NAME=task_db
      - TASK_POSTGRES_USER=postgres
      - TASK_POSTGRES_PASSWORD=1
      - TASK_ACCESS_KEY_SECRET_VALUE=SkFfMHotTzhxbEtRQ1AyZkwxVU1LQjVoXyxFNnNkdHdhQkRac0ZueTlJLnchTnY3eDVKQ1lHM1J1T3JNaT9YcFRFR2h2NA==

  task-db:
    image: postgres:15-alpine
    volumes:
      - /var/lib/postgresql/tms/task
    container_name: task-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1

  frontend-server:
    build: ./frontend
    container_name: frontend-server
    ports:
      - "8282:80"